import 'package:hive_flutter/hive_flutter.dart';

// ---------------------------------------------------------------------------
// HiveSetup
//
// Centralizes all Hive TypeAdapter registration and box initialization.
// Called once at app startup in main().
//
// TypeAdapters are generated by hive_generator. After adding a new @HiveType
// annotated model, run:
//   dart run build_runner build --delete-conflicting-outputs
// ---------------------------------------------------------------------------
class HiveSetup {
  HiveSetup._();

  /// Box name constants — single source of truth to prevent typo bugs.
  static const String scanHistoryBoxName = 'scan_history';

  static Future<void> registerAdaptersAndOpenBoxes() async {
    // --- Register TypeAdapters ---
    // Uncomment each line as you create the corresponding model + generated adapter.
    // The typeId in each @HiveType annotation must be unique across the entire app.

    // if (!Hive.isAdapterRegistered(0)) {
    //   Hive.registerAdapter(ScanHistoryModelAdapter()); // typeId: 0
    // }

    // --- Open Boxes ---
    // Boxes are like tables. Open them once at startup; they remain open for
    // the app's lifetime and are closed automatically when the app terminates.
    await Hive.openBox<dynamic>(scanHistoryBoxName);
  }
}